# ==============================================================================
# FILE: Generator/Agents.py  
# DESCRIPTION: Agent factory for the Generator workflow
# ==============================================================================
import asyncio
import sys
import os
from pathlib import Path

# Add the core directory to the Python path
core_path = Path(__file__).parent.parent.parent / "core"
sys.path.insert(0, str(core_path))

from autogen import ConversableAgent
from .StructuredOutputs import get_llm
import logging

logger = logging.getLogger(__name__)

async def define_agents():
    """Define agents with unified transport channel and dynamic hooks"""
    
    logger.info("🏗️ [GENERATOR] Creating agents...")
    import time
    start_time = time.time()

    # Get structured LLM configs for each agent (streaming handled by AG2 IOStream)
    logger.debug("🔧 [GENERATOR] Loading LLM configs...")
    _, llm_cfg_context = await get_llm("ContextVariablesAgent")
    _, llm_cfg_agents = await get_llm("AgentsAgent")
    _, llm_cfg_handoffs = await get_llm("HandoffsAgent")
    _, llm_cfg_orch = await get_llm("OrchestratorAgent")
    
    # Get LLM configs for UI agents (APIKeyAgent, UserFeedbackAgent)
    _, llm_streaming = await get_llm("base")
    logger.debug("✅ [GENERATOR] LLM configs loaded (streaming handled by AG2 IOStream)")
    
    agents = {}
    
    # NOTE: UserProxyAgent is now auto-generated by groupchat_manager.py
    # based on workflow.json human_in_the_loop flag. No need to create it here.
    
    # Context Agent - The initiating agent that analyzes concept overview
    logger.debug("🔧 [GENERATOR] Creating ContextAgent...")
    agents["ContextAgent"] = ConversableAgent(
        name="ContextAgent",
        system_message="""You are the ContextAgent, the first agent in the workflow generation process. Your job is to analyze the concept overview and determine a single agentic function that can enhance the UI/UX or efficiency of the user's concept.

TASK:
1. Read and analyze the concept overview provided in the context variables
2. Identify ONE key agentic function that would most improve the user experience or operational efficiency
3. Provide a brief, focused summary of what automation will be built

GUIDELINES:
- Keep your response SHORT for token cost efficiency (2-3 sentences maximum)
- Focus on the SINGLE most impactful agentic capability
- Consider UI/UX improvements, workflow automation, or efficiency gains
- Provide enough context so other agents understand what they're building
- No structured outputs needed - just clear, concise prose

EXAMPLE RESPONSE:
"Based on the concept overview, I recommend building an automated customer inquiry routing agent that analyzes incoming messages and intelligently assigns them to appropriate team members. This will reduce response times and improve customer satisfaction by ensuring queries reach the right expertise immediately."

YOUR TASK:
Analyze the concept overview and identify the single most valuable agentic function to enhance this application.""",
        llm_config=llm_streaming,
        human_input_mode="NEVER",
        max_consecutive_auto_reply=2
    )
    
    # Agents Agent - Now runs AFTER ContextAgent
    logger.debug("🔧 [GENERATOR] Creating AgentsAgent...")
    agents["AgentsAgent"] = ConversableAgent(
        name="AgentsAgent", 
        system_message="""You are the AgentsAgent, responsible for designing and defining agents for an AG2 (formerly Autogen) workflow.

CONTEXT:
The ContextAgent has already analyzed the concept overview and identified the key agentic function to build. Build upon their analysis to create a comprehensive agent architecture.

IMMEDIATE TASK:
Based on the ContextAgent's analysis and the concept overview in context variables, design all necessary agents for this workflow and output structured agent definitions in JSON format.

OUTPUT FORMAT:
Your response must be valid JSON following this exact schema:

{
  "agent_list": [
    {
      "name": "agent_variable_name",
      "display_name": "Agent Display Name", 
      "agent_type": "ConversableAgent",
      "system_message": "Detailed instructions defining agent's exact role and tasks",
      "human_input_mode": "NEVER",
      "max_consecutive_auto_reply": 10
    }
  ]
}

ANALYSIS APPROACH:
1. Review the ContextAgent's identified agentic function
2. Read the concept overview from context variables
3. Design agents that will implement the identified automation effectively
4. Consider all necessary agent roles: coordinators, specialists, validators, etc.

YOUR TASK:
Design a complete agent architecture that implements the agentic function identified by ContextAgent, outputting structured JSON with all necessary agent definitions.""",
        llm_config=llm_cfg_agents,
        human_input_mode="NEVER",
        max_consecutive_auto_reply=2
    )
    
    # Context Variables Agent - Now runs AFTER AgentsAgent
    logger.debug("🔧 [GENERATOR] Creating ContextVariablesAgent...")
    agents["ContextVariablesAgent"] = ConversableAgent(
        name="ContextVariablesAgent",
        system_message="""You are the ContextVariablesAgent. Your job is to analyze the concept overview, ContextAgent's identified agentic function, AND the agent definitions created by AgentsAgent for an AG2 (formerly Autogen) workflow.

Based on:
1. The ContextAgent's analysis of the key agentic function to build
2. The concept overview provided in the context variables
3. The agent definitions that were created by AgentsAgent
4. What context variables those agents will need to function properly

OUTPUT FORMAT:
Your response must be valid JSON following this exact schema:

{
  "context_variables": [
    {
      "name": "variable_name",
      "extraction_code": "concept_data.get('KeyName', '')",
      "description": "Description of what this variable represents", 
      "default_value": "''"
    }
  ]
}

ANALYSIS APPROACH:
1. Review the ContextAgent's identified agentic function
2. Examine the concept overview to understand the application domain and requirements
3. Review the agent definitions to understand what data they'll need
4. Create context variables that extract relevant information from the concept data
5. Consider variables for: project metadata, domain-specific data, user requirements, technical specifications, business requirements

YOUR TASK:
Analyze all previous agent outputs and create context variables that will enable the agents to implement the identified agentic function effectively.""",
        llm_config=llm_cfg_context,
        human_input_mode="NEVER",
        max_consecutive_auto_reply=2
    )

    # Orchestrator Agent - Moved before HandoffsAgent
    logger.debug("🔧 [GENERATOR] Creating OrchestratorAgent...")
    agents["OrchestratorAgent"] = ConversableAgent(
        name="OrchestratorAgent",
        system_message="""You are the OrchestratorAgent. Your task is to output only the structured YAML defining the orchestration settings for this workflow that will be used to generate workflow.json.

OUTPUT FORMAT:
Your response must be valid YAML and follow this exact schema—do not include any narrative, explanations, or markdown:

orchestration:
  initiating_agent: "<agent_name>"
  recipient: "<recipient_agent_name>"
  pattern: "<orchestration_pattern>"
  initial_message: "<initial_message_text>"
  max_turns: <integer>

CRITICAL INSTRUCTIONS:
1. 99.9% of the time, the initiating_agent should be "user" (lowercase, no capital U)
2. The recipient is typically the first workflow agent that should receive the initial message
3. Pattern should be one of: "DefaultPattern", "AutoPattern", "RoundRobinPattern", "RandomPattern", "ManualPattern"
4. Initial_message should be clear and actionable for the recipient agent
5. Max_turns should be reasonable for the workflow complexity (typically 10-50)

IMPORTANT: Always use "user" (lowercase) as the initiating_agent unless there's a very specific reason to use a different agent.

YOUR TASK:
1. Analyze the workflow requirements and agent structure
2. Set initiating_agent to "user" (99.9% of cases)
3. Determine the appropriate recipient agent for the initial message
4. Choose the orchestration pattern that best fits the workflow
5. Craft an initial_message that clearly communicates the workflow goal
6. Set appropriate max_turns for the workflow complexity
7. Output only valid YAML for the orchestration section.""",
        llm_config=llm_cfg_orch,
        human_input_mode="NEVER",
        max_consecutive_auto_reply=2
    )

    # Handoffs Agent - Moved after OrchestratorAgent  
    logger.debug("🔧 [GENERATOR] Creating HandoffsAgent...")
    agents["HandoffsAgent"] = ConversableAgent(
        name="HandoffsAgent", 
        system_message="""You are the HandoffsAgent, responsible for designing handoff logic for AG2 (formerly Autogen) workflows.

CONTEXT:
You have access to all previous agent outputs:
- ContextAgent's identified agentic function
- AgentsAgent's agent definitions  
- ContextVariablesAgent's context variables
- OrchestratorAgent's orchestration settings

YOUR TASK:
Design comprehensive handoff rules that control how agents pass control to each other, and output them in structured JSON format.

OUTPUT FORMAT:
Your response must be valid JSON following this exact schema:

{
  "handoff_rules": [
    {
      "source_agent": "AgentName",
      "target_agent": "NextAgentName",
      "handoff_type": "after_work",
      "condition": null,
      "context_expression": null,
      "priority": 1,
      "description": "Clear description of this handoff rule"
    }
  ],
  "workflow_pattern": "sequential",
  "termination_strategy": "automatic"
}

HANDOFF TYPES EXPLAINED:

1. "after_work" - Default routing when agent completes its task
   - Use for: Sequential workflows, primary flow paths
   - Example: ResearchAgent → AnalysisAgent → WriterAgent

2. "llm_condition" - Content-based routing using LLM analysis
   - Use for: Smart routing based on message content
   - Requires: "condition" field with routing prompt
   - Example: "Route to TechnicalAgent if the query is technical in nature"
   - Priority: Lower number = higher priority (1 = highest)

3. "context_condition" - State-based routing using context variables
   - Use for: Routing based on conversation state/variables
   - Requires: "context_expression" field with boolean expression
   - Example: "user_tier == 'premium'" or "attempt_count > 3"

TARGET AGENTS:
- Agent names from AgentsAgent's output
- "user" - Return control to user for input
- "terminate" - End the workflow

WORKFLOW PATTERNS:
- "sequential" - Linear A → B → C flow
- "conditional" - Smart routing based on conditions  
- "parallel" - Multiple agents can be active
- "hub_and_spoke" - Central router with specialist agents

TERMINATION STRATEGIES:
- "automatic" - Workflow ends when task complete
- "manual" - User decides when to end
- "conditional" - End based on specific conditions

DESIGN PRINCIPLES:
1. Create clear primary paths using "after_work" handoffs
2. Add conditional routing for smart decision making
3. Always provide termination paths to "terminate" or "user"
4. Use priority ordering for multiple LLM conditions on same agent
5. Consider escalation paths for complex scenarios
6. Ensure every agent has at least one exit path

ANALYSIS APPROACH:
1. Review the agent definitions to understand each agent's role
2. Map the logical flow from start to completion
3. Identify decision points that need conditional routing
4. Design primary paths with after_work handoffs
5. Add LLM conditions for content-based decisions
6. Add context conditions for state-based decisions
7. Ensure proper termination handling

YOUR TASK:
Design comprehensive handoff rules that create a smooth, logical workflow from the initial user input through to completion, using the agent definitions and orchestration settings from previous agents.""",
        llm_config=llm_cfg_handoffs,
        human_input_mode="NEVER",
        max_consecutive_auto_reply=2
    )

    # API Key Agent
    logger.debug("🔧 [GENERATOR] Creating APIKeyAgent...")
    agents["APIKeyAgent"] = ConversableAgent(
        name="APIKeyAgent",
        system_message="""You are the APIKeyAgent. Your responsibilities:

1. Analyze the workflow requirements and identify what external API services will be needed
2. For each required service, request the API key from the user using the modular UI tool system
3. The tools will be automatically registered via the workflow.json configuration

WORKFLOW TOOL USAGE:
The modular tool system will provide you with tools to request API keys. Use them when needed.

COMMON SERVICES THAT MAY REQUIRE API KEYS:
- OpenAI - For GPT models and OpenAI API access
- Anthropic - For Claude models  
- Azure OpenAI - For Azure OpenAI services
- Google - For Google AI/Gemini models
- Hugging Face - For Hugging Face model access
- GitHub - For GitHub API access (if generating repos)

YOUR TASK:
1. Analyze what the workflow will need to do
2. Determine which external APIs/services are required  
3. Use the provided tools to collect necessary API keys from the user
4. Wait for the user responses before proceeding to the next agent""",
        llm_config=llm_streaming,
        human_input_mode="NEVER",
        max_consecutive_auto_reply=2
    )

    # User Feedback Agent
    logger.debug("🔧 [GENERATOR] Creating UserFeedbackAgent...")
    agents["UserFeedbackAgent"] = ConversableAgent(
        name="UserFeedbackAgent",
        system_message="""You are the UserFeedbackAgent. Your responsibilities:

1. Collect the structured outputs from all previous agents (ContextVariablesAgent, AgentsAgent, OrchestratorAgent, HandoffsAgent, and APIKeyAgent)
2. Assemble them into the final workflow manifest as YAML format
3. Use the modular tool system to offer the generated workflow.yaml file to the user

WORKFLOW TOOL USAGE:
The modular tool system will provide you with tools to offer file downloads. Use them when needed.

WORKFLOW YAML STRUCTURE:
Combine all agent outputs into a complete workflow.yaml file with sections:
- agents: (from AgentsAgent output)
- context_variables: (from ContextVariablesAgent output)  
- orchestration: (from OrchestratorAgent output with fields: initiating_agent, recipient, pattern, initial_message, max_turns)
- handoffs: (from HandoffsAgent output)

ORCHESTRATION STRUCTURE:
The orchestration section should include:
- initiating_agent: (typically "user" in lowercase)
- recipient: (first workflow agent to receive initial message)
- pattern: (DefaultPattern, AutoPattern, etc.)
- initial_message: (clear workflow instruction)
- max_turns: (workflow turn limit)

YOUR TASK:
1. Gather all the structured outputs from the previous agents
2. Assemble them into a valid workflow.yaml file with proper orchestration structure
3. Use the provided tools to offer the file download to the user
4. Wait for user interaction before completing""",
        llm_config=llm_streaming,
        human_input_mode="ALWAYS",
        max_consecutive_auto_reply=2
    )

    # Log completion
    agent_count = len(agents)
    duration = time.time() - start_time
    logger.info(f"✅ [GENERATOR] Created {agent_count} agents in {duration:.2f}s")
    logger.debug(f"🔍 [GENERATOR] Agent names: {list(agents.keys())}")

    # NOTE: Tool registration is now handled by the modular tool system
    # via workflow.json configuration and the WorkflowToolRegistry
    logger.info("🔧 [GENERATOR] Tools will be registered via modular tool system")

    return agents
