# ==============================================================================
# FILE: core/workflow/agents.py  
# DESCRIPTION: Workflow-agnostic agent factory - loads from modular YAML configs
# ==============================================================================
import asyncio
import sys
import os
import logging
from pathlib import Path
from typing import Dict, Any

from autogen import ConversableAgent
from .file_manager import workflow_file_manager

logger = logging.getLogger(__name__)

async def define_agents(workflow_name: str):
    """
    Define agents with unified transport channel - fully workflow-agnostic.
    Loads agent configurations from modular YAML files.
    
    Args:
        workflow_name: Name of the workflow to load agents for
        
    Returns:
        Dictionary of agent instances
    """
    
    logger.info(f"🏗️ [AGENTS] Creating agents for workflow: {workflow_name}")
    import time
    start_time = time.time()

    # Load workflow configuration using file manager
    workflow_config = workflow_file_manager.load_workflow(workflow_name)
    
    if not workflow_config:
        logger.error(f"❌ [AGENTS] No configuration found for workflow: {workflow_name}")
        return {}
    
    agent_configs = workflow_config.get('agents', {})
    
    # Handle nested structure: agents -> agents -> agent_definitions
    if 'agents' in agent_configs:
        agent_configs = agent_configs['agents']
    
    logger.debug(f"🔧 [AGENTS] Loading {len(agent_configs)} agent definitions")
    
    # Get all unique LLM config types needed
    llm_configs = {}
    
    # Collect unique LLM config types
    unique_llm_types = set()
    for agent_name, agent_config in agent_configs.items():
        llm_type = agent_config.get('llm_config_type', 'base')
        unique_llm_types.add(llm_type)
    
    # Load all required LLM configs
    logger.debug("🔧 [AGENTS] Loading LLM configs...")
    
    # Import structured outputs dynamically based on workflow
    try:
        from .structured_outputs import get_llm_for_workflow
        
        for llm_type in unique_llm_types:
            _, llm_config = await get_llm_for_workflow(workflow_name, llm_type)
            llm_configs[llm_type] = llm_config
            
    except ImportError:
        # Fallback to core config if structured outputs not available
        logger.warning("📝 [AGENTS] Structured outputs not available, using core config")
        from core.core_config import make_llm_config
        
        for llm_type in unique_llm_types:
            _, llm_config = await make_llm_config()
            llm_configs[llm_type] = llm_config
    
    logger.debug("✅ [AGENTS] LLM configs loaded")
    
    agents = {}

    # NOTE: UserProxyAgent is auto-generated by orchestration_patterns.py
    # based on workflow config human_in_the_loop flag. No need to create it here.
    
    # Create agents dynamically from YAML configuration
    for agent_name, agent_config in agent_configs.items():
        logger.debug(f"🔧 [AGENTS] Creating agent '{agent_name}' dynamically from YAML config...")

        llm_type = agent_config.get('llm_config_type', 'base')
        llm_config = llm_configs.get(llm_type, llm_configs.get('base'))

        # Create the agent with configuration from YAML
        agent = ConversableAgent(
            name=agent_name,
            system_message=agent_config.get('system_message', ''),
            llm_config=llm_config,
            human_input_mode=agent_config.get('human_input_mode', 'NEVER'),
            max_consecutive_auto_reply=agent_config.get('max_consecutive_auto_reply', 2)
        )

        agents[agent_name] = agent

        # Generic debugging for any agent created
        logger.debug(
            f"✅ [AGENTS] Created '{agent_name}' with human_input_mode='{agent.human_input_mode}', "
            f"max_consecutive_auto_reply={agent.max_consecutive_auto_reply}, llm_type='{llm_type}'"
        )

    # Completion log remains generic
    agent_count = len(agents)
    duration = time.time() - start_time
    logger.info(f"✅ [AGENTS] Created {agent_count} agents for '{workflow_name}' in {duration:.2f}s")
    logger.debug(f"🔍 [AGENTS] Agent names: {list(agents.keys())}")

    # NOTE: Tool registration is handled by the modular tool system
    logger.info("🔧 [AGENTS] Tools registration handled by modular tool system")

    return agents